version: '2'

services:
  mshudx.vote.web:
    image: user/mshudx.vote.web${TAG}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    external_links:
      - redis
networks:
  default:
    external:
      name: vote-dev